language: node_js
node_js: "10"

script:
  - cd todolist-react && yarn && yarn build && cd ..
  - cd todolist-react-redux-saga && yarn && yarn build && cd ..
  - cd todolist-react-redux-thunk && yarn && yarn build && cd ..
  - cd todolist-angular && npm install && npm run build && cd ..
  - cd todolist-angular-ngxs && npm install && npm run build && cd ..
  - mkdir build
  - mv todolist-react/build build/todolist-react
  - mv todolist-react-redux-saga/build build/todolist-react-redux-saga
  - mv todolist-react-redux-thunk/build build/todolist-react-redux-thunk
  - mv todolist-angular/dist/todolist-angular build/todolist-angular
  - mv todolist-angular-ngxs/dist/todolist-angular-ngxs build/todolist-angular-ngxs

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: build
  on:
    branch: master
